"""New Orleans neighborhood statistical areas (data.nola.gov dataset exvn-jeh2)."""

NEIGHBORHOODS: tuple[str, ...] = (
    "Algiers Point",
    "Audubon",
    "B. W. Cooper",
    "Bayou St. John",
    "Behrman",
    "Black Pearl",
    "Broadmoor",
    "Bywater",
    "Central Business District",
    "Central City",
    "City Park",
    "Desire Area",
    "Dillard",
    "Dixon",
    "East Carrollton",
    "East Riverside",
    "Fairgrounds",
    "Filmore",
    "Fischer Dev",
    "Florida Area",
    "Florida Dev",
    "French Quarter",
    "Freret",
    "Garden District",
    "Gentilly Terrace",
    "Gentilly Woods",
    "Gert Town",
    "Hollygrove",
    "Holy Cross",
    "Iberville",
    "Irish Channel",
    "Lake Catherine",
    "Lake Terrace & Oaks",
    "Lakeshore - Lake Vista",
    "Lakeview",
    "Lakewood",
    "Leonidas",
    "Little Woods",
    "Lower Garden District",
    "Lower Ninth Ward",
    "Marigny",
    "Marlyville - Fontainebleau",
    "Mid-City",
    "Milan",
    "Milneburg",
    "McDonogh",
    "Navarre",
    "New Aurora - English Turn",
    "Old Aurora",
    "Pines Village",
    "Plum Orchard",
    "Pontchartrain Park",
    "Read Blvd East",
    "Read Blvd West",
    "Seventh Ward",
    "St. Anthony",
    "St. Bernard Area",
    "St. Claude",
    "St. Roch",
    "St. Thomas Dev",
    "Tall Timbers - Brechtel",
    "Touro",
    "Treme - Lafitte",
    "Tulane - Gravier",
    "U.S. Naval Base",
    "Uptown",
    "Viavant - Venetian Isles",
    "Village de l'Est",
    "West End",
    "West Lake Forest",
    "West Riverside",
    "Whitney",
)
